version: '3.8'
services:
  pathfiner-ssl:
    image: vaahtokarkki/pathfinder-ssl
    environment:
      - MTLS=true
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - ./certs:/certs
